### ISSUE TITLE
关于参考图像pose的问题

### ISSUE THREAD

**Issue by potentialming** [Francis-Rings/StableAnimator#23]
感谢您出色的工作，我这里有个问题想向您请教一下，我看你们的模型架构与Controlnext的比较接近，请问是否参考了他们的代码？如果是的话，我注意到Controlnext的模型在推理时需要额外拼接引用图像的姿势，而你们的代码好像优化了这一部分。想请教下是如何做到的？

**Comment by Francis-Rings** [comment]
Hi, the given pose sequence is directly fed to the PoseNet of StableAnimator without any concatenation during inference. The outputs of the PoseNet are element-wise added to the main latent in the diffusion model.

**Comment by potentialming** [comment]
感谢回复，还想问一下，你们训练时使用unet的参数是全部都训练吗？这得需要多少的显存啊？

**Comment by Francis-Rings** [comment]
Hi, in the SVD U-Net, only the attention components are trainable. The training process requires 70GB of VRAM due to the mixed-resolution (512x512 and 576x1024) training pipeline. However, if you train StableAnimator exclusively on 512x512 videos, the VRAM requirement is reduced to approximately 40GB. I will release the training code and training tutorial this Friday. Stay Tuned!

**Comment by potentialming** [comment]
非常棒，期待您的更新。

**Comment by xujinbao282** [comment]
Looking forward to it, great work
