### ISSUE TITLE
关于训练信息可以补充吗？

### ISSUE THREAD

**Issue by wangshankun** [Francis-Rings/StableAnimator#53]
请问不同分辨率的训练是分步骤训的吗？

训练集多少个视频，用了多少step效果收敛的， 能不能提供训练集下载地址呀

**Comment by Francis-Rings** [comment]
Hi, StableAnimator is trained using a mixed-resolution setting within an end-to-end pipeline. Videos in two resolution settings (512×512 and 576×1024) are combined and stored in two dataloaders, as detailed below.
```
iter1 = iter(train_dataloader_1)
iter2 = iter(train_dataloader_2)
list_0_and_1 = [0] * len_zeros + [1] * len_ones
random.shuffle(list_0_and_1)
for step in range(0, len(list_0_and_1)):
  current_idx = list_0_and_1[step]
  if current_idx == 0:
  try:
    batch = next(iter1)
  except StopIteration:
    iter1 = iter(train_dataloader_1)
    batch = next(iter1)
  elif current_idx == 1:
    try:
      batch = next(iter2)
    except StopIteration:
      iter2 = iter(train_dataloader_2)
      batch = next(iter2)
```
For more training details, please refer to the training tutorial in the README file. I recommend collecting at least 3,000 videos to fine-tune StableAnimator. If you prefer to train a LORA model, there is no need to gather thousands of videos. Regarding training convergence, it largely depends on the quality and scale of your dataset. The `train.py` includes an evaluation phase, allowing you to observe intermediate results and assess whether the model has converged. Due to company policy, I am unable to share the training dataset. However, you can collect videos from several social media platforms, such as TikTok and Bilibili.

**Comment by justinday123** [comment]
How much time did it cost for your train time?

**Comment by Francis-Rings** [comment]
> How much time did it cost for your train time?

Hi, I trained StableAnimator on 4 NVIDIA A100 80G GPUs for approximately 5 days.
